Added the Authentication and completed the all tasks
developerabhijeet/portal-management pull request #11
Opened 2024-01-19 14:30 UTC by chandraprakash9589

=>Added the roll based authentication in signup and login page .
=>Added  the user and email mention user can see only status functionality.
=>Fixed the status email reminder issues.

2024-01-19 17:21 UTC, developerabhijeet requested changes

2024-01-19 17:21 UTC, developerabhijeet commented on frontend/src/components/Attendance/pages/Dashboard.jsx
> +
do not use inline stylings

2024-01-19 17:21 UTC, developerabhijeet commented on frontend/src/components/Attendance/pages/MyDailyStatus.jsx
> +          .get(`${BaseURL}/tasks`, {
this can be optimise

2024-01-19 17:21 UTC, developerabhijeet commented on frontend/src/components/Attendance/pages/SendMyDailyStatus.jsx
> +  const [emailData, setEmailData] = useState([]);
why there are two states for email and email data?

2024-01-19 17:21 UTC, developerabhijeet commented on frontend/src/components/Attendance/pages/SendMyDailyStatus.jsx
> +          dueDate: startDate,
this function can also be optimised

2024-01-19 17:21 UTC, developerabhijeet commented on frontend/src/components/Attendance/pages/SendMyDailyStatus.jsx
> +                          <option value="Done">Done</option>
breakdown this component and create reusable inputs

2024-01-19 17:21 UTC, developerabhijeet commented on frontend/src/components/Auth/signup/signup.jsx
> +      } else {
optimise this and remove commented code

2024-01-19 17:24 UTC, chandraprakash9589 commented on frontend/src/components/Auth/signup/signup.jsx
> +      } else {
Sure sir

2024-01-22 11:07 UTC, developerabhijeet approved these changes

2024-01-22 11:07 UTC, merged